apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.codenow.componentRuntimeName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Values.codenow.componentRuntimeName }}"
data:
  nats_nkey: "U1VBR0tGWldCUjJNR1g3RlJOT1E1WEdISE1MM1RFTFVGS1MzQ0xSQk5CN0pPVTNNUEc2SVlRU0c1NApVQ0pPTVhMWDZKQ0Y3NEI2Qks1UUpLM1dPTUM2R0s2VlVURkZHRk5VTlQzM1pRTDZXTUEyQjNYNw=="
  aws_s3_access_key_id: ""
  aws_s3_secret_access_key: ""
