apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.codenow.componentRuntimeName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Values.codenow.componentRuntimeName }}"
data:
  nats_nkey: {{ .Values.nats.nkey }}
  aws_s3_access_key_id: {{ .Values.s3.accessKeyId }}
  aws_s3_secret_access_key: {{ .Values.s3.secretAccessKey }}
