# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
configHash: "1" # configuration change detection
codenow:
  instance: ""
  applicationName: ""
  applicationRuntimeName: ""
  applicationVersion: ""
  componentRuntimeName: "aws-ecr-adapter"
  componentName: "aws-ecr-adapter"
  componentVersion: ${project.version}
  templateId: ""
  domainName: "stxcn.codenow.com"
  environmentId: ""

environmentVariables: {}

buildNumber: "${env.BUILD_NUMBER}"

image:
  repository: codenow-stxcn-docker.jfrog.io/codenow/aws-ecr-adapter
  pullPolicy: Always


configFiles: {}
environmentVariables: {}

fluentbit:
  istioProxy:
    enabled: true
    parser: envoy-logging-filter-parser
  parser: oxus-app-component-json

metricsPrometheusEnabled: false
metricsPrometheusStep: PT1M

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
