apiVersion: v1
kind: Secret
metadata:
  name: cn-aws-ecr-adapter-secret
  labels:
    app.kubernetes.io/name: cn-aws-ecr-adapter
    app.kubernetes.io/part-of: codenow
    app.kubernetes.io/component: adapter
data:
  nats_nkey: ""
  aws_s3_access_key_id: "4N84Z36QFSS4FPCOYXM7"
  aws_s3_secret_access_key: "YjA0gSsP8ErYAeetg9sJeJaeUbYWLM19dzetuVDD"